Repository Necron-Dev/EnchAddons, pull requests merged in 2025-03, with the labels that each got.

#5 feat: update README.md
  README.md
Labels: enhancement

#6 feat: add banner.png
  banner.png
Labels: enhancement

#10 fix: fix `InvincibilityTimer` being incompatible with Patcher's `Compact Chat`
  src/main/java/net/skymoe/enchaddons/impl/mixin/NetHandlerPlayClientMixin.java
Labels: bug

#11 fix: fix being unable to save config due to incorrect field type
  src/main/kotlin/net/skymoe/enchaddons/feature/invincibilitytimer/InvincibilityTimerConfig.kt
  src/main/kotlin/net/skymoe/enchaddons/impl/config/feature/InvincibilityTimerConfigImpl.kt
Labels: bug

#15 fix: forgot init HypixelModAPI
  src/main/kotlin/net/skymoe/enchaddons/impl/hypixel/HypixelModAPILoader.kt
Labels: bug

#18 release: v0.2.0
  gradle.properties
Labels: Release
